wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.12
    start_time: 1654573871
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      3:
      - 7
      - 23
      4: 3.9.12
      5: 0.12.17
      8:
      - 2
      - 5
