wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss_iter
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss_iter
      5: 1
      6:
      - 1
    python_version: 3.9.7
    start_time: 1654179710
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 7
      - 23
      4: 3.9.7
      5: 0.12.17
      8:
      - 5
input_dim:
  desc: null
  value: 784
lr:
  desc: null
  value: 0.01
num_classes:
  desc: null
  value: 10
